### ISSUE TITLE
ELK 스택 컨테이너 문제 해결

### ISSUE THREAD

**Issue by Tae4an** [Tae4an/HaptiTalk#25]
## 초기 문제 발견
Docker Compose로 ELK 스택을 시작했을 때 Elasticsearch 컨테이너가 반복적으로 재시작되는 현상이 발생했습니다. 다른 컨테이너(Kibana, Logstash)는 시작되었지만 Elasticsearch가 없어 연결에 실패했습니다.

### 1차 시도: 로그 확인
```bash
docker logs haptitalk-elasticsearch
```
로그에서 "max virtual memory areas vm.max_map_count" 오류를 발견했습니다. 이는 가상 메모리 설정 문제로 일반적인 해결책을 시도했습니다.

### 2차 시도: sysctl 명령어 적용
리눅스 환경에서 일반적으로 사용하는 명령어를 시도했습니다:
```bash
sudo sysctl -w vm.max_map_count=262144
```
하지만 MacOS에서는 이 방법이 직접 적용되지 않아 실패했습니다.

### 3차 시도: Docker 설정 파일 수정
Docker Desktop의 설정 파일을 수정해보았지만 변경사항이 적용되지 않았습니다:
```json
{
  "resources": {
    "memory": 4096,
    "swap": 1024
  },
  "kernelParams": [
    "sysctl.vm.max_map_count=262144"
  ]
}
```

### 4차 시도: 환경 변수로 해결
Docker Compose 파일에 환경변수를 추가했으나 여전히 문제가 지속되었습니다:
```yaml
environment:
  - bootstrap.memory_lock=true
  - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
```

### 5차 시도: Docker 가상 머신에 직접 접근
가상 머신에 직접 접근하여 설정을 변경하는 방법을 시도했습니다:
```bash
docker run -it --rm --privileged --pid=host alpine:latest nsenter -t 1 -m -u -n -i sh
sysctl -w vm.max_map_count=262144
```
이 방법으로 가상 메모리 설정 문제는 해결됐으나, 이제 디스커버리 설정 오류가 발생했습니다.

### 6차 시도: 디스커버리 설정 추가
`elasticsearch.yml` 파일을 수정하려 했으나, 컨테이너가 시작될 때마다 설정이 초기화되었습니다. 그래서 Docker Compose 환경변수에 추가했습니다:
```yaml
environment:
  - discovery.type=single-node
```

### 7차 시도: 볼륨 권한 문제
위 설정들을 적용했지만 여전히 컨테이너가 시작되지 않았습니다. 로그를 더 자세히 살펴보니 데이터 디렉토리 권한 문제가 발견되었습니다:
```
elasticsearch_1  | [1]: failed to obtain node locks, tried [/usr/share/elasticsearch/data]
```

데이터 디렉토리의 권한을 수정했습니다:
```bash
sudo chown -R 1000:1000 ./infrastructure/monitoring/elk/elasticsearch/data
```

## 최종 해결책
모든 문제를 해결하기 위해 다음 조치들을 함께 적용했습니다:

1. Docker VM의 가상 메모리 설정 증가:
```bash
docker run -it --rm --privileged --pid=host alpine:latest nsenter -t 1 -m -u -n -i sh
sysctl -w vm.max_map_count=262144
```

2. Docker Compose 파일에 필요한 모든 설정 추가:
```yaml
elasticsearch:
  image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
  environment:
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    - discovery.type=single-node
    - xpack.security.enabled=false
  volumes:
    - ./infrastructure/monitoring/elk/elasticsearch/data:/usr/share/elasticsearch/data
    - ./infrastructure/monitoring/elk/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
  ports:
    - "9200:9200"
    - "9300:9300"
  ulimits:
    memlock:
      soft: -1
      hard: -1
```

3. 데이터 디렉토리 권한 설정:
```bash
sudo chown -R 1000:1000 ./infrastructure/monitoring/elk/elasticsearch/data
```

4. 최종적으로 구성을 다시 시작:
```bash
docker-compose down
docker-compose up -d
```

이러한 모든 조치를 취한 후에야 Elasticsearch가 정상적으로 시작되었고, 이후 Kibana와 Logstash도 정상 작동하기 시작했습니다. 이 과정에서 Docker 컨테이너화된 Elasticsearch의 특징과 MacOS에서의 Docker 가상화 환경의 특성을 더 깊이 이해하게 되었습니다.
