### ISSUE TITLE
JWT 인증 및 프로필 조회 문제 해결

### ISSUE THREAD

**Issue by Tae4an** [Tae4an/HaptiTalk#62]
## 📋 문제 개요

**증상**: Flutter 앱에서 로그인 후 사용자 프로필 조회 시 지속적인 401 Unauthorized 오류 발생

**영향**: 사용자가 로그인은 성공하지만 프로필 정보를 가져올 수 없어 앱 사용 불가

### 1단계: 초기 증상 확인

```
flutter: ❌ 사용자 프로필 조회 실패: Exception: GET 요청 실패: Exception: API 요청 실패: 401 Unauthorized
```

- ✅ 로그인 API 성공
- ✅ JWT 토큰 수신 성공
- ❌ 프로필 조회 API 실패 (401 오류)

### 2단계: 서버 상태 확인

**라즈베리파이 서버 접속**: `ssh -i [SSH_KEY_PATH] [USERNAME]@[SERVER_ADDRESS]`

- ✅ 모든 마이크로서비스 정상 실행 중
- ✅ Auth Service 로그인 성공 로그 확인
- ✅ Kong API Gateway 정상 실행 확인
- ❌ User Service에서 401 오류 지속 발생

### 3단계: JWT 설정 검증

```bash
# Auth Service 환경변수
JWT_APP_KEY_ID=[JWT_APPLICATION_KEY_ID]

# Kong JWT 소비자 설정
key: "[JWT_APPLICATION_KEY_ID]"
```

- ✅ 환경변수와 Kong 설정 일치 확인
- ✅ Kong JWT 플러그인 올바르게 적용됨

### 문제 1: Authorization 헤더 오염

**발견**: 로그인 API(Public API)에 이전 토큰의 Authorization 헤더가 포함됨

```json
{
  "authorization": "Bearer [PREVIOUS_JWT_TOKEN]..."
}
```

**문제점**: 로그인 API는 인증이 불필요한 Public API인데 Authorization 헤더가 포함되어 보안 및 API 설계 원칙 위배

### 문제 2: JWT 토큰 구조 오류 (핵심 문제)

**JWT 표준 위반**: `kid` 필드가 payload에 포함되어 있었음

**잘못된 구조** (`api/auth-service/src/services/token.service.js`):

```jsx
const tokenPayload = {
    sub: user.id,
    email: user.email,
    type: 'access',
    kid: process.env.JWT_APP_KEY_ID  // ← 잘못된 위치 (payload)
};

const accessToken = jwt.sign(
    tokenPayload,
    JWT_CONFIG.ACCESS_TOKEN.SECRET,
    {expiresIn: JWT_CONFIG.ACCESS_TOKEN.EXPIRES_IN}
);
```

**올바른 구조**:

```jsx
const tokenPayload = {
    sub: user.id,
    email: user.email,
    type: 'access'
};

const accessToken = jwt.sign(
    tokenPayload,
    JWT_CONFIG.ACCESS_TOKEN.SECRET,
    {
        expiresIn: JWT_CONFIG.ACCESS_TOKEN.EXPIRES_IN,
        header: {
            kid: process.env.JWT_APP_KEY_ID  // ← 올바른 위치 (header)
        }
    }
);
```

### 1단계: Flutter AuthService 수정

**파일**: `lib/services/auth_service.dart`

**수정 내용**:
- 로그인 전 Authorization 헤더 제거 로직 추가
- 더 자세한 로그 출력을 위한 코드 개선
- 서버 응답 파싱 로직 강화

### 2단계: JWT 토큰 생성 로직 수정

**파일**: `api/auth-service/src/services/token.service.js`

**수정된 메서드**:
- `generateAccessToken()`
- `generateRefreshToken()`
- `generateSessionToken()`

**변경사항**: 모든 토큰 생성에서 `kid`를 header로 이동

### 3단계: Kong 환경변수 치환 문제 해결

**문제**: Kong 설정 파일에서 환경변수가 제대로 치환되지 않음

```yaml
# 문제가 있던 설정
key: "${JWT_APP_KEY_ID:-[DEFAULT_APP_KEY]}"
```

**해결책**: Kong Init Container 패턴 적용

```yaml
kong-init:
  image: alpine:latest
  container_name: [PROJECT_NAME]-kong-init
  environment:
    JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
    JWT_APP_KEY_ID: ${JWT_APP_KEY_ID}
  volumes:
    - ./infrastructure/api-gateway/kong.yml:/tmp/kong.yml.template:ro
    - kong_config:/tmp/kong_config
  command: >
    sh -c '
      apk add --no-cache gettext &&
      envsubst < /tmp/kong.yml.template > /tmp/kong_config/kong.yml &&
      echo "환경변수 치환 완료!"
    '
```

**결과**: 성공적인 환경변수 치환 확인

```json
{
  "data": [
    {
      "key": "[JWT_APPLICATION_KEY_ID]",
      "algorithm": "HS256",
      "secret": "[JWT_ACCESS_SECRET]"
    }
  ]
}
```

### 4단계: 새로운 문제 발견 - 500 Internal Server Error

JWT 인증 문제 해결 후 새로운 문제 발생:

```
flutter: ❌ 사용자 프로필 조회 실패: Exception: API 요청 실패: 500 Internal Server Error
```

**원인**: User Service에서 프로필이 없는 사용자에 대해 "Profile not found" 오류 발생

### 5단계: User Service 프로필 자동 생성 로직 구현

**파일**: `api/user-service/src/services/profile.service.js`

**수정된 로직**:

```jsx
// 데이터베이스에서 조회
let profile = await Profile.findByPk(userId);
if (!profile) {
    logger.warn(`프로필이 존재하지 않음 - 기본 프로필 생성: ${userId}`);

    // 프로필이 없으면 기본 프로필 생성
    profile = await this.createDefaultProfile(userId);
    return profile;
}
```

**추가된 메서드**:

```jsx
async createDefaultProfile(userId) {
    try {
        const profile = await Profile.create({
            id: userId
        });

        logger.info(`기본 프로필 생성 성공: ${userId}`);

        // Kafka 이벤트 발행 및 Redis 캐싱
        return profile.toJSON();
    } catch (error) {
        logger.error('Error creating default profile:', error);
        throw error;
    }
}
```

### 6단계: GitHub Actions를 통한 배포

**워크플로우**: `.github/workflows/backend-ci.yml` → `.github/workflows/raspberry-pi-deploy.yml`

**배포 결과**:

```
✅ user-service: ARM64 이미지 사용 가능
✅ 모든 서비스 이미지가 정상적으로 빌드되어 GitHub Container Registry에 업로드됨
```

### 7단계: User Service 배포 문제 해결

**문제**: User Service 컨테이너가 실행되지 않음

```bash
docker ps | grep user-service
# 결과: 컨테이너 없음
```

**원인**: Docker Compose에서 로컬 빌드 방식 사용 중이었는데 서버에 소스 코드 없음

```yaml
user-service:
  build:  # ← 문제 (서버에 소스 코드 없음)
    context: ./api/user-service
    dockerfile: Dockerfile
```

**해결책**: GitHub Container Registry 이미지 사용으로 변경

```yaml
user-service:
  image: ghcr.io/[GITHUB_USERNAME]/[PROJECT_NAME]-user-service:develop
  platform: linux/arm64
```

### 성공 로그 확인

```bash
# User Service 정상 실행 확인
docker ps | grep user-service
# 결과: Up 11 seconds (healthy)

# 프로필 자동 생성 성공 로그
{"level":"info","message":"기본 프로필 생성 성공: [USER_ID]"}

# Flutter 앱 성공 로그
flutter: ✅ 프로필 조회 성공:
flutter: ✅ 실제 API 로그인 성공:
```

### 동작 순서

1. **첫 번째 요청**: 프로필이 없어서 자동으로 기본 프로필 생성 → 일시적 오류 발생
2. **두 번째 요청**: 이미 생성된 프로필을 조회 → 성공

### 기술적 교훈

1. **JWT 표준 준수**: `kid`는 반드시 header에 포함되어야 함
2. **환경변수 치환**: Kong과 같은 컨테이너에서 환경변수 치환 시 Init Container 패턴 활용
3. **마이크로서비스 데이터 일관성**: 사용자 생성 시 모든 관련 서비스에 데이터 생성 필요

### 운영적 교훈

1. **Docker Compose 일관성**: 로컬과 서버의 Docker Compose 설정 동기화 중요
2. **CI/CD 파이프라인**: GitHub Actions를 통한 체계적인 배포가 수동 배포보다 안전
3. **모니터링**: 실시간 로그 모니터링으로 문제 빠른 감지 가능

### 개선된 아키텍처

- ✅ JWT 인증 정상화
- ✅ 프로필 자동 생성 로직 구현
- ✅ Kong 환경변수 치환 안정화
- ✅ GitHub Container Registry 기반 배포 시스템 구축
